- test_gf_coverage.py
> fix logic in test_gf_coverage script

- .gitmodules
> fix submodule path

- Lib/gftools/util/glyphdata.py
- setup.py
> use pkg_resources to access Glyph*.xml files

- encodings/GF Glyph Sets/Vietnamese/README.md
> GF Glyph Sets/Vietnamese/README.md Updated

- encodings/GF Glyph Sets/README.md
Minor typo fix in readme document for the GF Glyph Sets
> Glyph Sets README typo fix

- setup.py
Just a small update for a new release on PyPI.
> Update setup.py for v0.2.0 release

- setup.py
Currently gftools on pypi has no project description: https://pypi.org/project/gftools/
This pull request fixes that issue
> Update setup.py with better project description for pypi

- bin/gftools-fix-nonhinting.py
Still backwards compatible with py2
> fix-nonhinting: make py3 compatible

- bin/gftools-fix-vf-meta.py
> gftools-fix-vf-meta: fix issues found Encode Sans

- bin/gftools-fix-isfixedpitch.py
Added simple script to set the post tables' isfixedpitch attrib to 1 if monospace else 0.
@thundernixon this should be a good starting point. I'd look into what other settings should exist for monospace fonts.
> WIP: gftools-fix-isfixedpitch.py added.

- bin/gftools-build-vf.py
The Public Sans project is looking for a fontmake build script in this issue: https://github.com/uswds/public-sans/issues/84
So I am updating this to the latest version in case they want to use it.
> Update variable font build script for public sans

- README.md
Fixes #106 
@chrissimpkins feel free to make any suggestions.
> Update README to include installation notes for Cairo, Harfbuzz and FreeType

- README.md
No issue for this; just noticed it was a broken link.
> README.md: Fix broken links

- bin/gftools-fix-weightclass.py
A simple script to fix a font's usWeightClass based on the font's filename. I need this for a project we have to release today so I'll merge it
> fix-weightclass added

- bin/gftools-check-gf-github.py
- Run on py3
- Use github api tokens instead of users username and password. This allows 2 factor accounts to work
- cleanup getting pagination results
> check-gf-github: update

- Lib/gftools/utils.py
- bin/gftools-qa.py
- requirements.txt
- setup.py
If a user is downloading fonts from google/fonts or a fork of it, the family's project files will also be included.
Solves #157
> Refactor functions to download fonts from github

- bin/gftools-qa.py
VFs were not grouping together with statics correctly. Code was also very unreadable
> qa: fix font grouping in QA.diffbrowsers

- bin/gftools-fix-isfixedpitch.py
> Set panosebProportion=9 when monospace

- bin/gftools-fix-isfixedpitch.py
> update rules for proper panose fixed pitch values

- bin/gftools-fix-fsselection.py
- Improve canonical error message
- Derive style info from the font filename not the fullpath
> fix-fsselection: improve script

- bin/gftools-add-font.py
- setup.py
Thanks @graphicore 
fixes #211
> add-font: encode as utf-8

- Lib/gftools/tests/test_usage.py
- bin/gftools-update-nameids.py
- setup.py
> update-nameids: use toUnicode()

- bin/gftools-add-font.py
Will stop https://github.com/google/fonts/issues/2559 from happening.
We'll still write an FB check though.
> add-font: do not rewrite subsets if metadata exists

- bin/gftools-push-status.py
Determine whether the families listed in to_sandbox.txt and to_production.txt in the google fonts dir have been pushed.
> gftools push-status added.

- .travis.yml
- Lib/gftools/packager.py
- Lib/gftools/template.upstream.yaml
- README.md
- bin/gftools-packager.py
- docs/gftools-packager/README.md
- setup.py
Tool to transfer font families from their upstream git repository to the google/fonts repository structure, taking care of all the details.
This introduces a new file to google/fonts, `{family_dir}/upstream.yaml`. 
~There's one hard coded `upstream.yaml` in the script, that simulates how a family that already has an `upstream.yaml`in google/fonts would behave. You can try it with "Gelasio".~
New dependencies in `setup.py`: `pygit2`, `strictyaml`
```
$ export GH_TOKEN=aaabbbcccYOURTOKEN
$ export VISUAL=gedit
```
(updated basic usage, comprehensive docs in the making)
```
$  gftools packager Gelasio ../googleFonts/
$  gftools packager Gelasio ../googleFonts/  -f
$  gftools packager Gelasio ../googleFonts/ -f -y
$  gftools packager Gelasio ../googleFonts/ -g
$ gftools packager …
```
> new tool: gftools packager

- Lib/gftools/packager.py
- Lib/gftools/template.upstream.yaml
> Gftools packager

- .github/workflows/publish-release.yml
> Checkout submodules into publish workflow

- Lib/gftools/fix.py
- Lib/gftools/tests/test_fix.py
This existed before I made the fix module.
Thanks to @vv-monsalve for finding this.
> Add ExtraBlack style

- Lib/gftools/packager.py
- Lib/gftools/template.upstream.yaml
- bin/gftools-packager.py
Add **provisonal** build feature. To be handled with care! 
~~NOTE: this is based on the state of the branch of PR #239 which should be merged first.~~
> [packager] provisional build feature

- Lib/gftools/fix.py
- Lib/gftools/stat.py
- Lib/gftools/tests/test_fix.py
- Lib/gftools/util/styles.py
- Lib/gftools/utils.py
- bin/gftools-fix-ascii-fontmetadata.py
- bin/gftools-fix-cmap.py
- bin/gftools-fix-dsig.py
- bin/gftools-fix-fsselection.py
- bin/gftools-fix-fstype.py
- bin/gftools-fix-gasp.py
- bin/gftools-fix-glyph-private-encoding.py
- bin/gftools-fix-hinting.py
- bin/gftools-fix-isfixedpitch.py
- bin/gftools-fix-nameids.py
- bin/gftools-fix-weightclass.py
This is a collection of improvements with three main goals:
* Move auxiliary functions out of font-fixing code and into appropriate utils library
* Move font-fixing actions out of scripts and into fix.py
* Encapsulate common "load a font / fix it / save it to .fix if it changed / report any messages" logic to FontFixer class.
>  Refactor fixes

- Lib/gftools/html.py
> gen-html: Fix crash when VF does not contain wght axis

- Lib/gftools/stat.py
- Lib/gftools/tests/test_stat.py
@RosaWagner Please check if this PR solves #297
> Update fvar instance ps names when using gen_stat_tables_from_config

- Lib/gftools/axisregistry/README.md
- Lib/gftools/axisregistry/grade.textproto
- Lib/gftools/axisregistry/optical_size.textproto
- Lib/gftools/axisregistry/width.textproto
- Lib/gftools/axisregistry/wonky.textproto
Use axis registry in google/fonts repo at commit https://github.com/google/fonts/commit/7d96a1096e3e297e1f533e4439694bfe10c19ce0
> Update axis registry

- Lib/gftools/builder/__init__.py
- setup.py
> builder: use DecomposeTransformedComponents filter

- .github/workflows/test.yml
> ci: fix mypy

- Lib/gftools/builder/schema.py
> Builder schema: Allow floats in STAT table

- setup.py
Fixes https://github.com/pypa/setuptools_scm/issues/605
> Cap setuptools_scm

- Lib/gftools/push-templates/index.html
- bin/gftools-push-stats.py
Fixes https://github.com/google/fonts/issues/3812
> push-stats: implement Dave C feedback

- Lib/gftools/builder/__init__.py
We currently only use babelfont to determine what the familyName should be. It seems tidier to just use glyphsLib, defcon etc in order to do this.
If we require babelfont in the future, I have no problems with readding it.
> builder: refactor so babelfont isn't needed

- Lib/gftools/axisreg.py
- Lib/gftools/builder/schema.py
- Lib/gftools/fix.py
- Lib/gftools/html.py
- Lib/gftools/packager.py
- Lib/gftools/stat.py
- Lib/gftools/util/filter_lists.py
- Lib/gftools/utils.py
- bin/gftools-add-designer.py
- bin/gftools-add-glyphs.py
- bin/gftools-build-vf.py
- bin/gftools-check-category.py
- bin/gftools-cldr.py
- bin/gftools-find-features.py
- bin/gftools-fix-ascii-fontmetadata.py
- bin/gftools-fix-gasp.py
- bin/gftools-fix-hinting.py
- bin/gftools-fix-isfixedpitch.py
- bin/gftools-fix-unwanted-tables.py
- bin/gftools-gen-html.py
- bin/gftools-lang-sample-text.py
- bin/gftools-lang-support.py
- bin/gftools-push-status.py
- bin/gftools-qa.py
- bin/gftools-tag-noto.py
- bin/gftools-udhr.py
- requirements.txt
- setup.py
Tidy up things a bit:
- Remove unused imports detected by pylint
- Unused requirement libraries
> Unused imports and libraries

- Lib/gftools/push-templates/index.html
- bin/gftools-push-stats.py
Include a table which contains info for every commit.
> push-stats: add commit table

- bin/gftools-gen-push-lists.py
> gen-push-lists: keep manually entered directories

- bin/gftools-add-font.py
> add-font: retain fallbacks

- Lib/gftools/encodings/GF Glyph Sets/README.md
- Lib/gftools/encodings/README.md
> Add README files to let people know files moved to a different git repo.

- bin/gftools-add-designer.py
Fixes #479.
@RosaWagner could you test this for me?
> add-designer: asciify filenames

- Lib/gftools/fix.py
> use wght default value to set VF usWeightClass

- Lib/gftools/builder/__init__.py
* Keep a list of created files - useful for zipping the output, checking into git, etc.
* Allow variable font builds to fail without killing the whole build.
> Two builder enhancements

- Lib/gftools/axisregistry/casual.textproto
- Lib/gftools/axisregistry/cursive.textproto
- Lib/gftools/axisregistry/fill.textproto
- Lib/gftools/axisregistry/flair.textproto
- Lib/gftools/axisregistry/grade.textproto
- Lib/gftools/axisregistry/italic.textproto
- Lib/gftools/axisregistry/monospace.textproto
- Lib/gftools/axisregistry/optical_size.textproto
- Lib/gftools/axisregistry/slant.textproto
- Lib/gftools/axisregistry/softness.textproto
- Lib/gftools/axisregistry/weight.textproto
- Lib/gftools/axisregistry/width.textproto
- Lib/gftools/axisregistry/wonky.textproto
1. add fallback_only and display_name fields
2. add fill.textproto
> update axis textproto

- bin/gftools-ufo-set-order.py
Set glyph order for a collection of ufos.
I'll add anchors and components when/if I need them.
Tool will fix https://github.com/TypeNetwork/Roboto-Flex/issues/230
cc @sannorozco
> ufo-set-order: added

- bin/gftools-ufo-setter.py
Set attributes for a collection of ufos from the cli.
> ufo-setter: added

- bin/gftools-ufo-fix-instances.py
Fix designspace instances so they are gf spec complaint:
https://github.com/googlefonts/gf-docs/tree/main/Spec#fvar-instances
> ufo-fix-instances: added

- bin/gftools-add-font.py
> add-font: add axis registry overrides

- bin/gftools-ufo-fix-instances.py
Currently, designspace instances are generated using the fvar default values when we should be using the default values from the GF axis registry where possible.
Designspace instance coords use designspace coords, not user space so this has been fixed as well using the `map_forward` method.
> ufo-fix-instances: use axis reg default vals instead of fvar default vals

- Lib/gftools/packager.py
Thought I'd open this before doing the full implementation since it may be controversial.
The aim of this PR is to allow users to fetch fonts/files from online archives such as Github releases. Imo font binaries should not be stored in repos. It is much nicer to create a tagged release which contains an archive which has the released font files e.g here's Roboto Serif's v1.007 release page:
Users can then get the files from this release by using the `archive` field in the upstream yaml file e.g
```
branch: main
archive: https://github.com/googlefonts/roboto-serif/releases/download/v1.007/RobotoSerifFonts-v1.007.zip
files:
variable/RobotoSerif[wght].ttf: RobotoSerif[wght].ttf
...
```
If folks do want this feature, I'll improve it before asking for a review.
> packager: get files from archives

- Lib/gftools/utils.py
> Use textprotos for sample text if none found in UDHR

- Lib/gftools/builder/__init__.py
- setup.py
Depends on https://github.com/googlefonts/fontmake/pull/874, https://github.com/googlefonts/ufo2ft/pull/604
Fixes https://github.com/googlefonts/fontmake/issues/872
cc @yanone @anthrotype
> builder: run filters in ufo lib.plist

- bin/gftools-fix-fsselection.py
Fixes #553
@emmamarichal I'll cut a new release after lunch.
> fix-fsselection: save output

- Lib/gftools/builder/__init__.py
Temp fix for https://github.com/googlefonts/ufo2ft/issues/621. I need this in order to generate some projects asap.
cc @simoncozens
> builder: set components filters so they are post filters

- Lib/gftools/fix.py
> Don't crash on removed name table entries

- bin/gftools-gen-push-lists.py
As discussed on call:
```
ofl/figtree # PR#4968
ofl/intertight # PR#4977
ofl/notosansethiopic # PR#4863
ofl/notosansethiopic/article # PR#4863
ofl/notoseriforiya # PR#4878
ofl/cormorantunicase # PR#4893
...
```
> Add PR ID to push lists

- bin/gftools-gen-push-lists.py
- Do not include include noto article dirs
- fix lang directory path
- order push lists
cc @vv-monsalve
> gen-push-lists: small fixes

- Lib/gftools/push.py
- bin/gftools-gen-push-lists.py
Finally decided to clean this module up a bit. I've added functions to transform the `lang` and `axisregistry` paths which has made the code easier to understand.
I've also added the path transform for `lang` paths.
Fixes #603
> push: cleanup and fix lang paths

- bin/gftools-add-font.py
Depends on #605 being merged first.
> add-font: add primary_script field

- bin/gftools-gen-push-lists.py
I tested it locally and it works as expected.
- All small fixes are going in Upgrade category
- Lang stuff are displaying in Sample texts category
- Axis registry only having axis registry paths
- Anything else goes in Other
cc @m4rc1e @vv-monsalve
> Clean up and fix Lang category

- Lib/gftools/push.py
@garretrieger pushed the lang/scripts changes to sandbox without reporting issues. Until contradicted, I think we should accept this path for the CI.
> Update push.py to accept scripts textproto path

- setup.py
Only merge once googlefonts/fontbakery#3946 has been merged.
> set protobuf to use same versions as fontbakery

- bin/gftools-fix-fstype.py
Fix 404. I'm just gonna merge this, it should be uncontroversial.
> Update link to new GF Guide

- Lib/gftools/fonts_public.proto
- Lib/gftools/fonts_public_pb2.py
This gives us the minisite_url field, making sure we don't overwrite it when updating things with the packager.
> Sync fonts_public.proto with internal

- Lib/gftools/builder/__init__.py
glyphsLib/fontmake now supports .glyphspackages so we should too.
> Support glyphspackages

- Lib/gftools/fix.py
> Stop removing the MVAR table

- Lib/gftools/scripts/gen_push_lists.py
It shouldn't remove sc families now.
cc @RosaWagner 
Fixes #642
> gen_push_lists: better filtering

- Lib/gftools/qa.py
- Lib/gftools/scripts/qa.py
Depends on https://github.com/googlefonts/diffenator2/pull/47 being merged first. This PR won't introduce any differences to the QA tool, Diffenator2's api has just changed.
> qa: Use diffenator2 v0.2.0

- pyproject.toml
Temporarily pin hyperglot so we don't run into https://github.com/rosettatype/hyperglot/issues/127
> pin hyperglot

- Lib/gftools/scripts/fix_instances.py
In the fix module, we have a function to fix a font's fvar instances. This pr adds a script which can run this function. @emmamarichal needs this for a project,
> fix_instances: script added

- Lib/gftools/builder/__init__.py
- Lib/gftools/builder/schema.py
- docs/gftools-builder/README.md
To be used with Glyphs sources.
> Add support for specifying custom GlyphData XML files

- docs/gftools-builder/README.md
Came across this in a config.yaml and had to look it up, and came here first :)
> Update gftools/docs/gftools-builder/README.md with stat flag info

- Lib/gftools/scripts/add_font.py
> add-font: keep sample text

- Lib/gftools/scripts/add_font.py
Saw same issue as in #693 so tried same technique
> stop packager from deleting minisite_url from metadata.pb

- Lib/gftools/utils.py
> Improve error message if download fails

- Lib/gftools/utils.py
> Don’t report Z... as a primary script

- Lib/gftools/builder/_ninja.py
This fixes issue https://github.com/googlefonts/gftools/issues/719
> Clean up build files after Ninja Builder is done

- Lib/gftools/packager.py
- Lib/gftools/scripts/add_font.py
- Lib/gftools/template.upstream.yaml
Still WIP. Need to test whether it can handle multiple classifications properly.
cc @eliheuer
> packager: add stroke and classifications fields

- .github/workflows/test.yml
Add some newer Pythons, remove EOL’d 3.7
> Update CI Pythons

- Lib/gftools/builder/__init__.py
> Run fix_hinted_font after adding VTT

- Lib/gftools/builder/_ninja.py
> Support a couple more fontmake args

- Lib/gftools/builder/__init__.py
- Lib/gftools/builder/_ninja.py
- Lib/gftools/builder/schema.py
- data/test/builder/basic_family_glyphs_0/config.yaml
- data/test/builder/check_compatibility_ufo_1/config.yaml
- pyproject.toml
> OTF Autohint in builder

- Lib/gftools/scripts/gen_push_lists.py
> gen-push-lists fix imports

- Lib/gftools/scripts/rename_glyphs.py
@RosaWagner use this tool to rename the glyphs in the vtt ttfs.
> rename-glyphs added. Rename glyphs in a font based on another font

- Lib/gftools/builder/__init__.py
> [builder] WOFF2 after VTT

- Lib/gftools/builder/dependencies.py
- Lib/gftools/scripts/font_dependencies.py
- pyproject.toml
- tests/test_dependencies.py
Add font dependencies to a font's Debg table or dump requirements from a font file.
Splits #779.
> font-dependencies: tool and module added

- Lib/gftools/scripts/font_tags.py
- Lib/gftools/tags.py
- Lib/gftools/utils.py
- tests/test_tags.py
Add module and tool to read and export Google font tagging sheet.
> font-tags: added

- Lib/gftools/utils.py
Need to check on an absolute path since "." won't work.
> fix is_google_fonts_repo checker

- Lib/gftools/scripts/manage_traffic_jam.py
cc @emmamarichal @vv-monsalve @eliheuer @RosaWagner
> manage-traffic-jam: set wrap columns for vimdiff inspect mode

- Lib/gftools/qa.py
- Lib/gftools/scripts/qa.py
- README.md
- pyproject.toml
Will merge once Behdad has finished and a new fontTools release is cut.
> qa: add interpolation checks

- .github/workflows/publish-release.yml
> use trusted publishers workflow (attempt 2)

- Lib/gftools/push/servers.py
- Lib/gftools/scripts/manage_traffic_jam.py
> manage-traffic-jam: add arg to repull family data

- Lib/gftools/gfgithub.py
- Lib/gftools/packager.py
In last Thursday's pipeline meeting, @yanone mentioned that he'd like the packager to submit draft prs. We liked the idea since a PR made by the packager made need further tweaking.
> packager: make prs draft

- Lib/gftools/subsetmerger.py
- bin/fonts-subset-support.py
- pyproject.toml
This is using the new API of the new glyphsets database.
However, since the code mentions "subsets" in several instances, please make sure whether the gftools code really wants glyphsets or subsets here. I have a feeling that it wants subsets and this code is really totally out of place.
> Glyphsets API change

- Lib/gftools/packager.py
- Lib/gftools/scripts/format_html.py
- Lib/gftools/utils.py
There's a script called `gftools format-html`, and it's also auto-formatting all incoming html files in the packaging process.
> Format HTML files

- Lib/gftools/push/servers.py
- Lib/gftools/push/trafficjam.py
- Lib/gftools/scripts/manage_traffic_jam.py
This PR caches the project board and fixes getting family version numbers from the api.
> manage-traffic-jam: improvements

- Lib/gftools/tags.py
> tags: Get tagging data from user form as well

- Lib/gftools/tags.py
Fixes https://github.com/google/fonts/pull/7401
> tags: raise error if spreadsheet contains duplicate families

- Lib/gftools/builder/operations/__init__.py
- Lib/gftools/utils.py
Fixes #869 
Aside: https://matklad.github.io/2022/10/24/actions-permissions.html
> Support project directories with spaces

- Lib/gftools/packager.py
> packager: add menu subset to template

- Lib/gftools/packager.py
- docs/gftools-packager/README.md
> packager: run tool from any branch and do not overwrite existing content

- Lib/gftools/packager.py
@yanone this pr will get a METADATA.pb file from a branch if one doesn't already exist in the main branch.
> packager: get METADATA.pb files from branch if one exists

- Lib/gftools/builder/__init__.py
- Lib/gftools/builder/recipeproviders/noto.py
- Don't validate against base schema, there's barely anything there
- black
- Allow ints in ranges
> [builder] Fix noto builds

- Lib/gftools/push-templates/index.html
- Lib/gftools/scripts/push_stats.py
- remove issues since they are no longer relevant for tracking purposes
- ensure end date is always today
Fixes https://github.com/google/fonts/pull/7511
> push-stats: update

- Lib/gftools/scripts/add_axis.py
> add-axis: add fallback_only field.

- Lib/gftools/logging.py
- Lib/gftools/packager.py
- Lib/gftools/push/items.py
- Lib/gftools/push/trafficjam.py
- Lib/gftools/scripts/add_font.py
- Lib/gftools/scripts/manage_traffic_jam.py
- Lib/gftools/scripts/packager.py
@vv-monsalve @emmamarichal please test this while I'm out. should solve the 1,000+ file changes.
> packager: use TreeBuilder to get minimal needed files

- Lib/gftools/scripts/remap_layout.py
I gave `thaw_lookuplist` the ability to take a parameters dictionary so that feature parameters (such as stylistic set names) could be persisted across remappings.
But I never gathered that parameters dictionary and just fed in an empty dictionary each time because I am lazy and stupid. Guess what? That causes problems! Like stylistic set names disappearing, as in https://github.com/TypeTogether/Playwrite/issues/41.
This PR bothers to save the feature parameters before remapping. Good grief.
> [gftools-remap-layout] Maintain feature parameters

- Lib/gftools/builder/operations/instantiateUfo.py
- Lib/gftools/builder/recipeproviders/googlefonts.py
- data/test/builder/basic_family_glyphs_glyphData/GlyphData.xml
- data/test/builder/basic_family_glyphs_glyphData/TestFamily.glyphs
- data/test/builder/basic_family_glyphs_glyphData/config.yaml
- data/test/builder/recipeprovider_noto_glyphData/GlyphData.xml
- data/test/builder/recipeprovider_noto_glyphData/TestFamily.glyphs
- data/test/builder/recipeprovider_noto_glyphData/config.yaml
- tests/test_builder.py
Apparently I’m the only one who uses this and it keeps breaking, so this time make sure it gets tested.
> Fix glyphData (again)

- Lib/gftools/push/trafficjam.py
> push: update labels

- Lib/gftools/packager.py
- Lib/gftools/scripts/add_font.py
> packager: use articles for new families

- Lib/gftools/builder/schema.py
- docs/gftools-builder/README.md
> [builder] Schema and README fixes

- Lib/gftools/tags.py
> tags: rename "Superelipse to Superellipse"

- Lib/gftools/builder/recipeproviders/googlefonts.py
Implements @arrowtype's suggestions for finding the instance name more comprehensively.
> [builder] Intuit instance names better, fixes #966

- Lib/gftools/builder/recipeproviders/googlefonts.py
> [builder] Handle small caps generation for split VFs

- Lib/gftools/subsetmerger.py
This improves the way that gftools-add-ds-subset chooses appropriate "donor" UFOs from a designspace to be merged in: first, it handles axes which have been renamed, by selecting sources based on axis tag instead; second, when a donor designspace has axes which are not present in the "recipient", it ensures that the default instance is chosen.
> Improve ds-subsetting

- Lib/gftools/packager/__init__.py
Noto has article and description, don't remove description
> [packager] Don't remove description for Noto fonts

- Lib/gftools/stat.py
Fixes https://github.com/fonttools/fonttools/pull/3566
> stat: validate AxisValues names are strings

- Lib/gftools/tags.py
@nyshadhr9 I'll update the family data as well.
> tags: add Monospace

- .github/workflows/test.yml
> ci: do not run tests that need secrets from forks

- Lib/gftools/push/servers.py
- Lib/gftools/scripts/manage_traffic_jam.py
> push: check servers are online before running tool

- Lib/gftools/builder/__init__.py
This is my first PR here, we a simple task (in appearance...). 
This should solve this issue: https://github.com/googlefonts/gftools/issues/875
I have no idea of the working process here, so please feel free to correct me and tell me how it works. I'm curious :)
@simoncozens @m4rc1e
> Clean up the build files

- Lib/gftools/packager/__init__.py
We need to Warn about this. It will have a FATAL status
> CJK subset restriction added to checklist

- Lib/gftools/subsetmerger.py
Fixes #1023, took me hours to debug that.
> Change source name before skipping merge logic

- Lib/gftools/builder/schema.py
- docs/gftools-builder/README.md
> Allow a localMetadata field in builder

- Lib/gftools/builder/__init__.py
@simoncozens I tried to make possible the choice of `True` or `False` for the clean up action.
Should solve this: https://github.com/googlefonts/gftools/issues/1014
> [Builder] Clean up option in config file

- Lib/gftools/packager/__init__.py
@m4rc1e 
I added a point to the checklist, for the tagging process
> [Packager] Update to-do list

- Lib/gftools/gfgithub.py
- Lib/gftools/packager/__init__.py
> packager: update pr title when updating a pr

- Lib/gftools/builder/operations/instantiateUfo.py
> [builder] Reconstruct the instance name from family+style

- .github/workflows/test.yml
@RickyDaMa your emoji snapped me outta the cba attitude so thanks.
> ci: install cairo on linux

- Lib/gftools/scripts/compare_meta.py
Compare dev, sandbox and production servers. cc @chrissimpkins
> compare_meta added

- Lib/gftools/builder/operations/buildStat.py
- Lib/gftools/builder/recipeproviders/googlefonts.py
- **Ruff lints**
- **Add all VFs to build stat operation**
> Build all STAT tables in builder

- Lib/gftools/builder/operations/fontc/__init__.py
to be used in conjunction with https://github.com/googlefonts/fontc/pull/1458
> [fontc] turn fontmake's --filter DecomposeComponents into fontc's --decompose-components

- Lib/gftools/qa.py
As per https://github.com/fonttools/fontspector/issues/142#issuecomment-2915589981, fontspector is a little different from fontbakery in that it does not probe the filesystem for files that you have not told it about. (This is because on platforms like WASM there may not even be a filesystem!) So for our QA tool to provide correct results, we need to explicitly hand it any files that we want testing - METADATA.pb, article/description, license, etc.
> Provide more files to fontspector

- Lib/gftools/scripts/gen_avar2.py
Some avar2 fonts may have axes that don't have any masters e.g the parametric axes can be used to derive wght and wdth axes. cc @agyeiarcher
> gen-avar2: include fvar axes that do not have masters

- Lib/gftools/builder/operations/glyphs2ds.py
- Lib/gftools/builder/recipeproviders/googlefonts.py
- Lib/gftools/builder/recipeproviders/noto.py
- Lib/gftools/builder/schema.py
- Lib/gftools/scripts/add_ds_subsets.py
- Lib/gftools/subsetmerger.py
- docs/gftools-builder/README.md
This improves the subset merger, and, significantly, adds a new parameter to the builder config for Google Fonts recipes:
```
includeSubsets:
- from:
repo: googlefonts/Montserrat@master
path: sources/Montserrat.designspace
name: GF_Latin_Core
```
> Builder: allow adding subsets

- Lib/gftools/scripts/gen_avar2.py
I forgot to update the gvar table axisCount and update the various varStores.
> gen_avar2: fix implementation
