googlefonts/gftools

test_gf_coverage.py
(issue #6)
And also https://github.com/googlefonts/fontbakery/issues/1466
=> new script: test_gf_coverage to tell us which characters in a TTF are not in any GF .nam subset.

bin/gftools-check-vf-avar.py
This script will generate a html doc which compares a family of static fonts against a family of variable fonts instances.
It works by overlaying the variable font instances on top of the static fonts. This should help us spot anything that may be off with a variable font's avar table.
*Variable font's avar table matches the static fonts*
*Variable font's avar doesn't match the static fonts*
It is not a beautiful script, but it will do until we get this functionality integrated into GF Regression.
=> Add check-vf-avar

bin/gftools-fix-vf-meta.py
This script will update the STAT and name table for each font in a set of
fonts, which make up a variable font family.
The first commit supports the following scenarios:
- A family composed of a single font
- A family composed of two fonts, one Italic the other Roman
We still need to support the other examples listed in the STAT table specification:
https://docs.microsoft.com/en-us/typography/opentype/spec/stat
Please note, once fontmake is able to build STAT/name tables for families, this script
should be deprecated.
This PR remains a WIP while we discover all the edgecases. This script will be updated as
we convert more families on GoogleFonts to be variable fonts.
Fixes #56 
Created due to https://github.com/googlei18n/fontmake/issues/436
Keep this open please
=> WIP: bin/fix-vf-meta.py: fix STAT and name tables for VF families

encodings/GF Glyph Sets/GF-latin-expert_unique-glyphs.nam, encodings/GF Glyph Sets/filter lists/nice names/expert_unique-glyphs.txt, encodings/GF Glyph Sets/filter lists/uni names/expert_unique-glyphs.txt, encodings/GF Glyph Sets/glyphTypeSorting/EXPERT_composites_207.txt
The Unicode character U+0149 `napostrophe` was deprecated and removed
in the following commit: ba769ed6b693e8018e0e17b4df9541cb7befcba2
However, `napostrophe.sc` was never removed. This commit removes all
unneeded references to `napostrophe.sc` in the encodings.
fixes #69
=> Remove napostrophe.sc from all encodings

bin/gftools-compare-font.py
This update changes the output formatting to improve legibility.
It also makes the print statements Python3 compatible.
Resolves: #73
=> Fix output formatting for gftools-compare-font.py

bin/gftools
There were some basic usability issues that needed to be addressed.
This commit makes the following changes to `bin/gftools`:
- Added a `-v/--version` flag, prints version number from `setup.py`.
- Added an ASCII graphic with built-in version number.
- Basic formatting work to conform to `pycodestyle`.
- Added a short list of basic command examples.
Resolves: #75
=> CLI main menu update: usability improvements

README.md, setup.py
I'm getting ready to make a new PyPI release with Python 3 support, these updates make it clear that gftools works with Python 3.
=> Update setup.py and READ.MD for Python 3 PyPI release 

bin/gftools-fix-vf-meta.py
- Downgraded STAT table
- fix psname
Fonts simply didn't work in Word because Ms Word doesn't yet support the latest STAT table version. I need to get in touch with MS about this.
=> fix-vf-meta.py: Fix script so fonts can work in MS Word

bin/gftools-build-vf.py
This is the python variable font build script I have been using, but all the settings have been moved to args so it's easier to maintain. 
For example, I'm using the following command to build Orbitron, run from the font repo root directory:
```
gftools build-vf --googlefonts ~/Google/fonts/ofl/orbitron --fontbakery --drawbot --ttfautohint "-I -W --increase-x-height=0 --stem-width-mode=sss --default-script=latn"
``` 
This will do the following:
1. Build the font with fontmake
2. Run ttfautohint with the given given args
3. Copy new fonts to the Google fonts directory
4. Generate new DrawBot specimens
5. Run FontBakery in the GoogleFonts directory
6. Add a new FontBakery report to the docs directory   
A video demo of how this works is here: https://www.youtube.com/watch?v=l59jWpiR3xs
=> Variable font build script: added

bin/gftools-add-font.py
Marc made a PR with some python3 updates but It was missing a python3, this pr just adds that.
=> Add missing header for add-font python3 update

Lib/gftools/utils.py, README.md, bin/gftools-add-font.py, bin/gftools-check-font-version.py, bin/gftools-qa.py, setup.py
Our GF QA uses three tools, fontbakery, fontdiffenator and diffbrowsers. This script simply orchestrates them. For making comparisons, it can fetch fonts from Google Fonts or a user's system.
The aim of this script is to reduce the whole QA process to a single click. I predominately rely on the following two commands:
**QAing new families**
`gftools qa [fonts] --fontbakery --plot-glyphs --browser-previews`
**QAing updated families which already exist on GF**
`gftools qa [fonts] -gf --fontbakery --plot-glyphs --diffbrowsers`
I found myself writing something similar whilst working on CI stuff. I think it's better to have a standalone script so that both Travis and individuals can use it. I also include it in my fontmake build scripts. Automated builds and tests are a true life saver.
For …
=> WIP gftools qa: added

bin/gftools-fix-vf-meta.py
This pr addresses the issues discussed in https://github.com/googlefonts/fontbakery/issues/2297. The nametable is now the standard nametable which fontmake generates, plus the necessary name records needed to make a STAT table which will work in MS Word etc.
=> fix-vf meta: Only add necessary STAT entries to nametable

bin/gftools-qa.py
GFR used to run on a digital ocean droplet. I now have an instance running on GCE. Apart from reducing the costs it means I can share the credentials with others more easily.
=> Use GFR instance which is hosted on Google Compute Engine

bin/gftools-fix-vf-meta.py
OS/2 weightClass values should be multiples of 100 for variable fonts according to an [FB check](https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/specifications/googlefonts.py#L3646-L3666)
=> gftools-fix-vf-meta: change OS/2 weightClass vals for Thin and ExtraLight

bin/gftools-qa.py
I've dropped this because the size is too small to worry about in most cases. Also by dropping it, Travis will shave off 5-7 mins per an instance/static font. This should help keep diffs under 50 mins.
=> qa: do not produce browser diff for all glyphs at 14px.

bin/gftools-fix-hinting.py
Enable bit 3 on a font's head table flags, if the font contains hinting
=> gftools-fix-hinting: added.

bin/gftools-qa.py
Script was lacking a doc string and argparse options weren't well explained.
=> gftools qa: Improve help instructions

bin/gftools-fix-fstype.py
```
print('font saved %s.fix' % font_path)
else:
print('SKIPPING: %s fsType is already 0' % font_path)
```
lines 44,46 were missing parentheses in call to print
=> fixed missing parentheses error in fix-fstype.py

bin/gftools-check-sandbox-family.py
This script enables us to swap any website's GF hosted fonts with the same fonts hosted on our sandbox . Once we've finished QAing a family and the family is sandboxed, this should be the final check imo.
Here's a [production vs sandbox gif](https://user-images.githubusercontent.com/7525512/52221219-9d420380-2898-11e9-963e-dbf177316963.gif) for IBM Plex Sans on https://www.designworkplan.com/
@chrissimpkins This approach may interest you for your projects.
This is still WIP. Needs px diffing etc
=> WIP: check-sandbox-family added

Lib/gftools/utils.py, bin/gftools-qa.py
Current implementation cannot get fonts from private github repos. Well, it's able to download them but github appends the user's token to the filename. This causes problems when FontQA attempts to match the fonts. This pr will strip the token from the filename. It also allows filenames which contains suffixes which are not styles e.g FontFamily-Regular-Android.ttf will now work.
=> qa: get fonts from private github repos

bin/gftools-qa.py
Browser previews were only being generated for a single font because the `diff_browsers` methods were being called after the for loop had finished. I'm pretty sure this could have been avoided if the formatting was better. I may run this script through [black](https://github.com/psf/black)
=> qa: fix browser-previews

bin/gftools-qa.py
This option will allow users to post report data to any pull request.
We currently have an argument called -ogh. This also allows users to post report data to github. However, the pull request or github dir must contain font binaries.
This arg is more flexible since fonts are not required. It allows users to build fonts using a CI such as travis and then run gftools on the built fonts and post the results back to the pr.
=> qa: add args.out_url

bin/gftools-qa.py
GF Regression's VM needed some maintenance (first time in a year). Once the changes had been made, the VM's ip address changed. I didn't realise that the address was ephemeral only. This means if the VM is restarted, a new address is assigned. Going forward this shouldn't happen since it now uses a static ip address. 
https://cloud.google.com/compute/docs/ip-addresses/
I apologise for the inconvenience. Fortunately the old ip address was only used here and in FB dashboard. I'll submit a pr to fb dashboard now and inform TN to upgrade gftools.
=> qa: Update GF Regression url

Lib/gftools/util/google_fonts.py, bin/gftools-add-font.py
Running `gftools add-font` on a variable font family should now work. I haven't gone overboard with the implementation since we'll probably need to refactor this script once we start pushing vfs with multiple axes.
Since we're not able to extract the style and weight info from a VF's filename, I've had to use the name table.
I've also tidied up `FileFamilyStyleWeight` func arg. It takes a path, not just a filename.
=>  add-font: Support variable fonts

Lib/gftools/util/google_fonts.py
After merging #154, it failed on some VFs because it was returning a float when our protobuf expects the weight to be an int.
=> VFWeight: return weight as int

bin/gftools-fix-unwanted-tables.py
This PR adds the `gftools-fix-unwanted-tables.py` script.  The script removes one or more "unwanted tables" from one or more fonts.  
The supported tables are defined as the following:
```python
UNWANTED_TABLES = {
'FFTM': 'Table contains redundant FontForge timestamp info',
'TTFA': 'Redundant TTFAutohint table',
'TSI0': 'Table contains data only used in VTT',
'TSI1': 'Table contains data only used in VTT',
'TSI2': 'Table contains data only used in VTT',
'TSI3': 'Table contains data only used in VTT',
'TSI5': 'Table contains data only used in VTT',
'prop': '', # FIXME: why is this one unwanted?
'MVAR': ('Produces a bug in DirectWrite which causes'
' https://bugzilla.mozilla.org/show_bug.cgi?id=1492477,'
' https://github.com/google/fonts/issues/2085')
}
```
File writes are in place.
By …
=> Add gftools-fix-unwanted-tables.py script

Lib/gftools/utils.py, README.md, bin/gftools-qa.py, setup.py
Many users only want the fix scripts. They do not require gftools qa.
If users install gftools without the QA dependencies and tries to run `gftools qa` an error is raised which points to our readme which has the further installation instructions.
cc @arialcrime
@chrissimpkins I will update both google/fonts and Google Sans travis files.
=> setup.py: Set QA dependencies as extra requirement

Lib/gftools/tests/test_usage.py, bin/gftools-rename-font.py
We already have a script to update individual name records. However, we don't have a script to update a font's family name well.
It isn't as simple as just updating nameID 1. You have to update the fullname, psname and other references which may exist, such as the copyright string.
This script will update all name records by doing the following:
- Find the existing family name. If nameID 16 exists, use this. If not, use nameID 1
- Loop through records and replace the following patterns:
- Name without spaces (used in full font name, version etc)
- Name with hyphens (used in ps name)
- Name with spaces
Each record that gets modified is output to the terminal.
```
marcfoley$ gftools rename-font.py /Users/marcfoley/Desktop/Faustina\[wght\].ttf "Faustina 2"
Updating font name records
Updating …
```
=> gftools rename-font added.

bin/gftools-fix-isfixedpitch.py
OS/2.panose.bPropotion, OS/2.xAvgCharWidth, hhea.advanceWidthMax
See fontbakery’s [com.google.fonts/check/monospace](https://github.com/googlefonts/fontbakery/blob/b096392a7e6bb922f122cecae14e20c2fb0472ca/Lib/fontbakery/profiles/name.py#L68)
=> fix-isfixedpitch: also fix other monospace defining values

bin/gftools-fix-isfixedpitch.py
The previous fixup didn’t actually fix the bit in the font.
=> fixup previous fix-isfixedpitch patch

bin/gftools-qa.py, setup.py
Current implementation will download fonts and include them in tempdirs. After running a QA, I've often wanted to inspect the fonts further. This pr will simply add the fonts to the output dir.
I've also tidied up the CLI docs a little.
=> qa: Include fonts in output dir

Lib/gftools/tests/test_qa.py, Lib/gftools/utils.py, bin/gftools-qa.py
This PR allows users to compare a family of variable fonts against another family of variable fonts. Comparisons are made between matching instances only.
When we release VFs with multiple axes, we'll need to rethink this approach.  No one sane will want to check hundreds of instances.
I still need to update GFRegression so users can select which instances they want to see. Atm it will display all matching instances in two sets of VFs. Unfortunately the Browserstack screenshot api has an image limit of ~10k vertical pixels. To work around this for static fonts, I send only 4 matching fonts at a time. I'll use the same approach for VFs but use instances instead.
=> qa: test VF families against VF families

bin/gftools-qa.py, setup.py
Previous implementation couldn't run groups of instances through diffbrowsers and browser-previews correctly. It created the necessary groups but every group would contain all VF instances.
=> qa: Group VF instances correctly

bin/gftools-add-font.py
This is a patch for https://github.com/google/fonts/issues/187.
It may or may not be the best solution for the problem, but as I understand it, we want to add `ext` subsets into metadata if fonts contain even a single glyph of a given `ext` subset. By setting the default `min_pct_ext` to `0.01`, this mean that if 1 glyph of up to 1000 is present from an `ext` encoding file, it will apply that subset label. Because Cyrillic has the most glyphs in an `ext` encoding file at 333 glyphs, this gives some headroom. 
It doesn't apply `ext` subsets to all fonts, so it seems to be doing the job.
There are still further edits to make to `add-font`, but this one should correct this specific issue in future uses.
=> lower minimum percentage needed to apply "ext" subset

Lib/gftools/util/filter_lists.py, Lib/gftools/util/google_fonts.py
This is to enable running the old tests build into util/google_fonts and util/filter_lists. It's not yet clear if these are still correct though.
=> [util] Fix main entry point tests.

bin/gftools-qa.py
`gftools qa` currently doesn't download fonts that reside in a `static` dir. This causes the fontbakery check `com.google.fonts/check/repo/vf_has_static_fonts` to fail, even though the directory exist. This PR will download the fonts within a static dir so this check no longer fails.
Fixes the false positive reported in  https://github.com/google/fonts/pull/2494#issuecomment-642527586
=> qa: download static fonts from github prs

bin/gftools-fix-vf-meta.py, bin/gftools-fix-weightclass.py, setup.py
Both scripts has issues with setting usWeightClass values correctly.
fix-vf-meta:
I remove the hairline style. Fixes #221 
fix-weightclass:
I've used the fontbakery.parse module. This script will now set the usWeightClass correctly for otfs, ttfs and vfs.
=> Update fix-weightClass and fix-vf-meta

bin/gftools-fix-isfixedpitch.py, setup.py
Found by @rosawagner when working on Syne, https://gitlab.com/RosaWagner/syne-typeface/-/blob/master/fonts/ttf/SyneMono-Regular.ttf
=> fix-isfixedpitch: fix crash when familyType == 0

Lib/gftools/packager.py, bin/gftools-add-font.py, bin/gftools-packager.py
Add the flag `--no-source` to remove the `source` key from `METADATA.pb`, because the backend systems currently can't handle the source key.
=> Gftools packager

setup.py
The issues mentioned for the pinning (https://github.com/python-pillow/Pillow/issues/4509 and https://github.com/python-pillow/Pillow/issues/4518) are now closed.
=> Unpin Pillow - issues that justified pinning are now closed

Lib/gftools/packager.py
See #238: trying to fix wrongly selected remote for PR
Fixes an issue that happened to me when testing this, unlikely in normal usage though
I don't know if `_pygit2.GitError: unsupported URL protocol` is fixed with this!
UPDATE:
also fix #233 remove redundant info from upstream.yaml, remove comments from upstream.yaml
=> Gftools packager: several issues

Lib/gftools/packager.py
Turns out I overlooked this common case in d84b6e5. Please merge.
=> [packager] Fix bad merge of data from METADATA.pb and upstream.yaml

.travis.yml, Lib/gftools/fix.py, Lib/gftools/tests/test_fix.py, bin/gftools-fix-dsig.py, bin/gftools-fix-font.py, bin/gftools-fix-fstype.py, bin/gftools-fix-hinting.py, bin/gftools-fix-nonhinting.py, bin/gftools-fix-unwanted-tables.py, bin/gftools-fix-weightclass.py
We have a collection of fix scripts which contain useful snippets of code that should reside in their own module imo. By converting these snippets into functions, we'll get better reuse. There's also a lot of duplication so I'd like to cut down on this.
My end goal is to keep the individual fix scripts (without changing their apis) but I also just want a single `gftools fix-font` script which should do everything.
@alerque are you opposed to this idea?
=> Add fix module

.github/workflows/publish-release.yml
Adds a new GitHub Action configuration that prepares and pushes a GitHub release and PyPI source dist + wheel release when a `v` prefixed version git tag is pushed.  It can live side-by-side with the Travis CI unit testing / type checking  configuration.
@m4rc1e you will need to add the following data to the repository "Secrets" settings:
- PyPI username as `PYPI_USERNAME`
- PyPI password as `PYPI_PASSWORD`
If those data are missing when you push a version tag, you'll get a GH release but the PyPI push will fail.
This Action automatically adds the following to the body of every release:
> Please see the root of the repository for the CHANGELOG.md
You'll need to change this line to something that is appropriate here.
=> Add GH Action GitHub + PyPI release automation on git version tag pushes

.gitignore, Lib/gftools/__init__.py, setup.py
If you browse the history of this repo and other repos I work on, I typically include a commit to bump the version number. This PR will use the version number from the git tag instead.
=> Use use_scm_version instead of manually bumping version number

Lib/gftools/util/google_fonts.py
I'm trying to use gftools.fix in a script, and found that it was making my logging code disappear. I tracked it down to the call to `from absl import app` in `gftools.utils.google_fonts`. This only needs to be imported when unit testing and when `gftools.utils.google_fonts` is run as `__main__`. This PR moves the import to within the `if __name__ == '__main__':` to avoid interfering with other modules' logging.
=> Change import order to fix logging bug

Lib/gftools/builder/__init__.py, Lib/gftools/stat.py, Lib/gftools/tests/test_stat.py, Lib/gftools/tests/test_usage.py, bin/gftools-gen-stat.py, data/test/builder_test.yaml, data/test/lora_stat.yaml
I've refactored the `stat.gen_stat_tables_from_config` function so we don't need to supply source files. Instead, we just specify the ttf filenames e.g 
Current:
```YAML
Family.glyphs:
- name: Weight
tag: wght
...
```
This pr
```YAML
Family[wght].ttf
- name: Weight
tag: wght
...
```
By doing this, I can reuse the function in `gftools gen-stat` without users needing to add the sources (in some projects, we may not even have sources).
cc @simoncozens. Still wip, will add some tests. I've also tidied up some functions since many of them were saving files in place so they didn't have good reuse etc.
=> Use ttfs filenames instead of src filenames when building stat tables from config

Lib/gftools/axisreg.py, Lib/gftools/utils.py, bin/gftools-push-status.py
I decided to refactor this script since we also need to check if the push files contain typos. I could've forced this feature in but the code was already a mess.
If you supply the arg `--lint`, it will check if all paths specified in the server files are valid directories e.g 
`gftools push-status path/to/google/fonts --lint`. I will hook this command up to the google/fonts ci as well.
If our push pipeline increases in complexity, we should probably move these functions to their own dedicated module etc. For now, I think it's still fine as a script.
=> Refactor gftools push-status

Lib/gftools/packager.py, bin/gftools-qa.py
Currently, the GF bot doesn't post a comment in pull requests made to google/fonts. I temporarily disabled it because the old implementation would make a zip file and post it to the GFR server. This feature is now redundant because we use github artifacts instead.
This PR will allow us to reenable the bot but it will only post the fontbakery results as a comment. If users want to see the full test results/files, they will have to download the github artifact instead.
By doing the above, I can finally drop the GFR server for good since no services use it. I plan to keep it online for ~5 months but it will be retired.
@graphicore I've added another Github helper function to the packager, `create_github_issue`. I hope you don't mind? I'm tempted to move the git functionality out of packager …
=> QA: Update posting results to github issues/prs

bin/gftools-push-status.py
I just spoke to Nyshadh and he confirmed that including individual file paths for the axis registry is correct.
Currently, the push-status linter will only pass if all paths are directories.
=> push-status: Lint axis registry files

Lib/gftools/builder/__init__.py, bin/gftools-builder.py
Fixes https://github.com/googlefonts/gftools/issues/290
=> Gftools builder cleanup

Lib/gftools/html.py
Currently, we use `dirs_exist_ok=True` in `shutil.copytree`. This arg is only supported in Python3.8+.
=> Remove >= py3.8 shutil arg

Lib/gftools/builder/__init__.py, Lib/gftools/fix.py
This is a followup to pull request #296 that was automatically closed by mistake when this project renamed its **"master"** branch to **"main"**.
**Be sure to also read all the comments posted in the original PR (#296)**
Original PR description as submitted on  by @m4rc1e:
----
The builder will post process built fonts by calling the `gftools.fix.fix_font` function. This function has an additional arg called `include_source_fixes` which will hotfix a font (we advise that users fixes the sources). This PR will allow users to specify in their config file that they want to enable these fixes.
----
**Be sure to also read all the comments posted in the original PR (#296)**
=> Builder: Add includeSourceFixes to config file

Lib/gftools/html.py
Forgot to include the `template_dir` argument if the class needs to be partitioned.
=> gen-html: fix custom template dir

Lib/gftools/builder/__init__.py
Currently, `set([x.info.familyName for x in self.masters.values()])` doesn't work because `self.masters.values()` is a nested list structured as `[src1->[master1, master2], src2->[master1, master2]]`. To fix, I do another loop in `self.masters.values()` so i access the individual masters. 
Fixes #314 
cc @simoncozens.
=> builder: Fix getting familyName if config does not specify one

.github/workflows/test.yml
It looks like your default branch changed from `master` -> `main` and your Actions config defines runs on pushes to and PR's against `master`:
```yaml
on:
push:
branches: [master]
pull_request:
branches: [master]
```
This changes the config to `main`.  I *think* that this should address #320 
**Update** Confirmed: Closes #320
=> Convert GitHub Actions configuration to main branch

Lib/gftools/builder/__init__.py
`instance_ufo` and `master_ufo` should be deleted when `cleanUp` is set to true. Fixes https://github.com/googlefonts/gftools/issues/290#issuecomment-768457334
=> builder: Fix cleanUp

Lib/gftools/builder/__init__.py
This fixes #326 ([\[builder\] Make static OTFs optional](https://github.com/googlefonts/gftools/issues/326)) by adding a `buildOTF` parameter, and also adds a `buildTTF` parameter
=> [builder] Add buildOTF config parameter

Lib/gftools/builder/__init__.py
I merged #309 prematurely. This PR solves two issues.
1. I was calling the args for in the wrong order for `gen_static_font`
2. Filenames will be incorrect if the familyName and styleName isn't included for each instance. Solution is to generate the static font first and then assemble the filename from the font's name table.
=> Builder: fix instances

Lib/gftools/builder/__init__.py, Lib/gftools/fix.py
This PR solves two issues regarding VF names:
- `gftools builder` currently generates the axes in a vf filename in non-alphabetical order. They should be ordered alphabetically
- `gftools.fix` cannot fix a VF's name table. We can now fix VF name tables because the updateNameTable PR in fontTools has been merged and a new release cut.
=> Fix vf name table and builder vf filename

Lib/gftools/builder/__init__.py
Currently, we use the axisOrder parameter to construct VF filenames. This doesn't work correctly since a VF filename must only list the axes which are in the font, not all the axes which make up a family.
This issue becomes apparent when you have a VF family which consists of multiple fonts e.g:
Current implementation:
`MyFamily[wdth,wght,ital].ttf`
`MyFamily-Italic[wdth,wght,ital].ttf`
Neither font has an `ital` axis in the fvar tables so they shouldn't be included in the filename 
This pr will produce the following:
`MyFamily[wdth,wght].ttf`
`MyFamily-Italic[wdth,wght].ttf`
=> Fix vf filename round 2

Lib/gftools/builder/__init__.py
config["axisOrder"] may be undefined, this makes it default to the fvar order as mentioned in the doc.
=> builder: axisOrder defaults to fvar order

bin/gftools-packager.py
```
Changes "Allow executing the bash command in stored in the "build" key of upstream-conf, if present."
to      "Allow executing the bash command stored in the "build" key of upstream-conf, if present."
```
=> Packager: Fix typo in packager -B help

docs/gftools-packager/README.md
A CLI example line was missing the packager argument, this could be confusing and cause someone to get stuck of frustrated. I also removed a redundant and awkward "set up" from the related copy.
```
-    $ gftools familysans.upstream.yaml path/to/google/fonts/clone -fy
+    $ gftools packager familysans.upstream.yaml path/to/google/fonts/clone -fy
```
=> Packager readme: Fix CLI command with missing argument

Lib/gftools/stat.py
Currently, the opsz AxisValues will be elided twice. Once for the font's opsz default and again for the axis registry opsz default. We only want the font's opsz default.
=> stat: fix opsz elided value

Lib/gftools/builder/__init__.py, Lib/gftools/builder/schema.py, Lib/gftools/tests/test_builder.py, bin/gftools-builder.py
As suggested in issue #345. I need some feedback to make sure I'm going in the right direction.
So far, if I change `sources` to something like `sssources` in `sources/config.yaml`, I get the following error that includes the original traceback and some more helpful error messages giving hints on how to fix the problem:
```
$ gftools builder sources/config.yaml
Traceback (most recent call last):
File "/Users/Air/GF-2021/python/gftools/bin/gftools-builder.py", line 86, in <module>
builder.build()
File "/Users/Air/GF-2021/python/gftools/Lib/gftools/builder/__init__.py", line 145, in build
self.build_variable()
File "/Users/Air/GF-2021/python/gftools/Lib/gftools/builder/__init__.py", line 238, in build_variable
for source in self.config["sources"]:
KeyError: 'sources'
Error: A key in the …
```
=> Builder: Add error handling to check config files

Lib/gftools/builder/__init__.py, Lib/gftools/builder/schema.py, Lib/gftools/stat.py
Fixes #333
Users will need to declare format 4 axisValues in a separate section in their builder files. This mimics the implementation in fontTools where format4 axisValues are declared in a different variable in `buildStat`.
```
stat:
- name: Weight
tag: wght
values:
- name: Regular
value: 500
- name: Bold
value: 700
statFormat4: # <--- new section
- name: "Echo Fox"
location:
wght: 400
- name: "Echo Space"
location:
wght: 700
```
A stat table also needs to be declared in order for this to work.
=> builder: add support for STAT format4 axisValues

bin/gftools-add-designer.py
Had some complaints that the href urls were missing double quotes.
=> add-designer: format ahref links correctly

Lib/gftools/fix.py
Fontbakery problem detection and gftools fixing has got out of sync again. (*as will always happen when the detection and the fixes are in different places...*) As per https://github.com/googlefonts/fontbakery/issues/3398, we don't want fonts to have a DSIG table:
> In fact, I think we should flip the check to WARN people if a DSIG is found at all, and tell them to remove it.
=> Don't add dummy DSIG by default any more

Lib/gftools/fix.py
Guess what! It's another [fontbakery check](https://github.com/googlefonts/fontbakery/issues/3357) that got out of sync with the fix script!
=> Drop Debg table on fix

bin/gftools-add-designer.py, requirements.txt, setup.py
Installing gftools on M1 is obnoxiously slow because there isn't a wheel for pandas and it has to be built from scratch for every venv you install it into, and it takes *ages*. And you don't even need it 90% of the time! It's only used if you're using `gftools add-designer` *and* your input is an Excel spreadsheet.
Now that we're using the gftools-builder in UFR, and hence gftools is migrating towards more of a general userbase kind of thing, we need to be more aware of this kind of stuff.
This PR removes the pandas dependency, but tells you off if you do `gftools add-designer --spreadsheet` without pandas installed.
=> Require pandas at runtime only

bin/gftools-gen-push-lists.py
This tool generates the [to_production.txt](https://github.com/google/fonts/blob/main/to_production.txt) and [to_sandbox.txt](https://github.com/google/fonts/blob/main/to_sandbox.txt) files based on the card labels in the [traffic jam](https://github.com/google/fonts/projects/1).
@RosaWagner Could you quickly test this?
=> gen-push-lists added

.github/workflows/test.yml, Lib/gftools/packager.py, Lib/gftools/util/google_fonts.py
Atm when we push a new family using the packager, it will write the language fields without including the comments. We discovered this in, https://github.com/google/fonts/pull/4215/files#diff-b6d066da27817af5009644b06c6baf1d3536cc27dd1449982d6fa016840a9555
This PR writes the comments by using the WriteProto function which is also used in `add-font` and `lang-support`
=> packager: retain language field comments

Lib/gftools/builder/__init__.py, Lib/gftools/builder/autohint.py, Lib/gftools/builder/schema.py
The Noto build scripts pass a `-D<script>` argument to ttfautohint to enable script-specific hinting adjustments. This is a nice idea, and we should do it if possible. Also, the way Noto implements it is [horrible and arbitrary](https://github.com/googlefonts/noto-source/blob/3eab4dae98b0a40d38d216cab2a66b32000f3bfc/misc_scripts/publish-one-noto-font.sh#L48) and I'd like to move Noto's build scripts to cleaner code based on gftools where possible.
This checks whether a font file has a clear "winning" script (defined as having more than twice as many code points as any other script in the font) and, if ttfautohint has a script-specific handler for that script, passes the appropriate `-D` flag.
=> Detect script and pass to ttfautohint

Lib/gftools/packager.py, bin/gftools-packager.py
This PR removes the `--no-source` flag since our METADATA.pb files now accept the source field.
This also fixes #494
=> packager: rm --no-source flag

bin/gftools-ufo-transfer-data.py
Transfer data from one set of ufos to another. You can also match ufos by a glyph hash which is useful if filenames etc have been changed.
So far I've only added metrics, kerning, anchors. Will add more as I need them.
=> ufo-transfer-data: added

Lib/gftools/github.py, Lib/gftools/packager.py, bin/gftools-qa.py
The packager module is very big, and contains lots of code, not all of which is related to packaging; in addition, the GitHub-y bits of it are also used by gftools-qa. I'm hoping to use them for something else too, but they need disentangling first.
I've tested that gftools qa still works after this, but not the packager bits.
=> Move Github client from packager to own module

bin/gftools-add-font.py, bin/gftools-ufo-fix-instances.py
It appears that when the axisreg code was split out (see #515 #516 ), a couple of instances of axisreg were missed, causing gftools packager to now fail.
This PR corrects the two that I found.
=> Fixing missing axisregistry items

Lib/gftools/builder/__init__.py
I'm extending the builder for the Noto project; not an upstreamable extension - the idea is to fetch other Noto sources and merging subsets from them into the UFO while building. To do this, I need to extend the YAML schema to allow me to define the subsets in the config file. Currently I can't do that without major surgery. With this two-liner, the schema becomes inheritable.
=> [Builder] Make the schema inheritable

Lib/gftools/actions/__init__.py, Lib/gftools/actions/checkgooglefonts.py, Lib/gftools/actions/checkversionbump.py, Lib/gftools/actions/notobuilder.py, Lib/gftools/actions/qa2issue.py, Lib/gftools/actions/updateupstream.py, Lib/gftools/builder/__init__.py, Lib/gftools/builder/schema.py, requirements.txt, setup.py
The idea here is that there are certain (complex) steps we need to perform as part of GitHub actions in the googlefonts-project-template repo. If those steps lived in the googlefonts-project-template repo itself, we would lose control over the ability to maintain them, as they would be forked into all of the downstream repos. But if the code to perform those steps is part of gftools, then we can roll out updates just by doing another gftools release. The GitHub actions don't use the venv (because that's used for font building and is frozen, so that won't get updates either); instead they explicitly grab the latest version of gftools and run the actions outside the venv. So they're always up to date as of when the Action is run.
The scripts I've added are:
* `checkgooglefonts`: Very simple …
=> Add some scripts to be used in GH Actions

Lib/gftools/builder/__init__.py, Lib/gftools/builder/schema.py
Currently people using the packager type in certain values manually at the command line. Which is fine - except in the context of continuous deployment and unattended builds. If we store this information in the config.yaml file we can get hold of it later.
=> Add a category option to the builder config

Lib/gftools/utils.py, bin/gftools-qa.py
Now we are using GitHub release more, it becomes useful to QA a font against the previous release. e.g.
```
$ bin/gftools-qa.py -arb https://github.com/notofonts/limbu/releases/download/NotoSansLimbu-v2.002/limbu-2.02.zip -f fonts/ttf/Limbu-Regular.ttf --diffenator
```
This implements the `-arb` argument to gftools-qa.
=> Allow gftools-qa to download fonts from a URL

Lib/gftools/builder/__init__.py, Lib/gftools/tests/test_usage.py, data/test/Libre-Bodoni/AUTHORS.txt, data/test/Libre-Bodoni/CONTRIBUTORS.txt, data/test/Libre-Bodoni/FONTLOG.txt, data/test/Libre-Bodoni/OFL.txt, data/test/Libre-Bodoni/README.md, data/test/Libre-Bodoni/requirements.txt, data/test/Libre-Bodoni/sources/LibreBodoni-Italic.glyphs, data/test/Libre-Bodoni/sources/LibreBodoni.glyphs, data/test/Libre-Bodoni/sources/config.yaml
If a config file contains 2 or more sources, the second sources onwards will inherit the previous source's args. We want fresh args for each source. 
Hence why the ci complains in https://github.com/eliheuer/hasubi-mono/runs/6088671254?check_suite_focus=true
Fixes https://github.com/googlefonts/googlefonts-project-template/issues/72
Apologies for crappy explanation. Haven't slept well and I'm having a new floor laid. It's louder than a Dutch Gabber rave.
=> builder: ensure fontmake args are reset when generating fonts from each source file

bin/gftools-add-font.py
Two fields in a font's METADATA.pb are used by Noto fonts. These need to be preserved when upgrading a font with add-font.
=> Maintain Noto metadata

Lib/gftools/builder/__init__.py
I had an idea (in a6d9b067) that we should allow variable builds to fail and then track whether or not they succeeded by looking at the `.outputs` list.
In retrospect, this was a bad idea. If someone's said in the config file that they want a variable build, they should get an error if they don't get a variable build.
Fixes #503.
=> Die noisily when variable fonts fail to build

Lib/gftools/ufomerge.py
`ufo2._path` can be `None`, which makes `Path(ufo2._path)` fail.
=> ufomerge.py: Fix handling of missing font path

Lib/gftools/push.py
In https://github.com/google/fonts/pull/4679 we can see that Rod has changed the paths so they're specific to their backend. Currently, this makes our CI fail. In order to fix this, I modify the file paths so they match theirs and then check.
cc @RosaWagner
=> push-status: fix paths for checking languages

Lib/gftools/packager.py
This adds articles to the packager's allowlist. I need them for Noto and I had a few options here:
* Just keep this to my Noto gftools branch: possible but I'm trying to reduce divergence.
* Use `--no-allowlist`: but sanity checking is a good thing!
* Allow it for everyone: least bad option, probably won't be used by anyone other than Noto, but also it allows for the future possibility of having articles about library fonts.
=> [packager] Add article/ARTICLE.en_us.html to allowlist

Lib/gftools/templates/text.html
Currently, ltr is used for all scripts. This means we're having issues when proofing rtl scripts such as Arabic. I've simply used the html `dir="auto"` to enable this functionality.
*Noto Sans Arabic now rtl*
cc @simoncozens
=> gen-html: auto set script direction

Lib/gftools/utils.py
Currently we use UDHR to get some sample text, and then look in gflanguages' sample text collection if we got *nothing*. But we hardly ever get nothing at all, because there may be punctuation etc. in the font. (Even spaces!)
So this is more aggressive, and uses the gflanguages sample texts to try and get more text if we don't have complete coverage of the font's encoded characters.
=> Try harder to get more sample text

Lib/gftools/builder/__init__.py, Lib/gftools/builder/schema.py
Expose the reverse outlines, remove overlaps and expand features to instance arguments in the config.yml.
Expanding features is on by default because it's the only default that makes sense.
I chose to only expose these three, because GFBuilder calls fontmake's internals directly, bypassing the argument parser. I don't want to duplicate the logic of the parser.
Closes #301 
Closes #558 
Closes #581
=> Expose more fontmake args in the config

Lib/gftools/scripts/add_axis.py
We've decided that we won't be adding fallbacks to custom axes anymore. We only need to declare a single default axis value going forward.
=> add-axis: do not include fallbacks

Lib/gftools/ufomerge.py
When determining which glyphs to merge, we add glyphs to the glyphset `glyphs`. This used to be a set, but recently became a dictionary; however, the code to add glyphs via layout closure has not been updated.
=> Fix closure handling of ufomerger

Lib/gftools/builder/__init__.py, Lib/gftools/builder/schema.py
We recently moved to gftools v0.9.23 and noticed some of our Glyphs-based families stopped building correctly. Instead generating static fonts for each export in Glyphs, only the masters were built.
I believe the change in https://github.com/googlefonts/gftools/commit/bfb90fadbfde4431828f80b531f202da4a64eb0d is the cause. We have quite a few families that are interpolatable but not variable. That means that glyphs can be interpolated between some masters, but not all masters, so enabling the creation of variable fonts (through `buildVariable`) wouldn't help. I have attached an example Glyphs file (excuse my terrible design skills) of a family with some compatible masters using interpolation.
[Example.zip](https://github.com/googlefonts/gftools/files/10793928/Example.zip)
We would like to …
=> Add option to interpolate between masters for static fonts.

Lib/gftools/builder/__init__.py, Lib/gftools/fix.py, Lib/gftools/scripts/fix_family.py, Lib/gftools/scripts/fix_font.py
Atm, if you use `fix_font` or `fix_family`, fixes are applied in place. Unfortunately, the COLR fixes won't be applied since `fix_colr_v1_add_svg` needs to return a new TTFont instance since we're calling an external tool using subprocess. This PR changes `fix_family` and `fix_font` so they don't fix inplace but return TTFont instances instead.
cc @yanone
=> fix: return a new TTFont instance when running fix_font and fix_family

Lib/gftools/builder/__init__.py, Lib/gftools/builder/schema.py
Partly fixes #660 by allowing Viv and myself to disable Fontmake's compatibility checker.
Allowing the builder to take arbitrary args is tricky since we currently check if a user's config file has the correct args and they're also the correct type.
=> builder: add arg to enable or disable fontmake's check-compatibility

Lib/gftools/builder/__init__.py, Lib/gftools/fix.py
We currently generate the stat tables and then post process the fonts. If a STAT table uses nameID 2 or 17 in an axisValue, these may be changed by the post processing step. By post processing the fonts first, we ensure that the STAT table doesn't change.
cc @RosaWagner
=> builder: gen stat tables after post processing fonts

Lib/gftools/builder/__init__.py, Lib/gftools/builder/schema.py
This add the useMutatorMath paramater to call fontmake with `--use-mutatormath` for extrapolation or anisotropic locations when generating instances.
=> Add option to interpolate with MutatorMath (for extrapolation, anisotropic locations)

Lib/gftools/builder/__init__.py
The `check_compatbility` option was recently added in #662. Unfortunately this causes builds for "plain" UFO files to fail, as the `run_from_ufos` function in fontmake does not accept a named `check_compatibility` argument. This produces the following error:
```
Traceback (most recent call last):
File "/usr/local/bin/gftools", line 8, in <module>
sys.exit(main())
File "/gftools/lib/python3.10/site-packages/gftools/scripts/__init__.py", line 91, in main
mod.main(args[2:])
File "/gftools/lib/python3.10/site-packages/gftools/builder/__init__.py", line 665, in main
builder.build()
File "/gftools/lib/python3.10/site-packages/gftools/builder/__init__.py", line 212, in build
self.build_static()
File "/gftools/lib/python3.10/site-packages/gftools/builder/__init__.py", line 460, in build_static …
```
=> Only pass check_compatibility option for run_from_glyphs or run_from_designspace

Lib/gftools/scripts/lang_support.py
This is a small fix which means that when new Noto families go through lang-support, they don't end up with a bazillion Latin languages supported just because they have a basic Latin subset in them.
=> Don't advertise Latin support for Noto fonts

Lib/gftools/push-templates/index.html, Lib/gftools/scripts/push_stats.py
Currently, each time we run the tool, it'll find all the issues from 2014 onwards. This PR implements caching by saving the results to a json file and if the tool is rerun, it'll only fetch issues from the date the tool was last run.
=> push-stats: cache issues

Lib/gftools/packager.py, Lib/gftools/scripts/add_font.py
Currently, when you use gftools packager on a new family, the description placeholder is "N/A". This PR will add the "To contribute, please see url" to the description.
cc @RosaWagner @emmamarichal
=> packager: add github url to new description files

Lib/gftools/push.py, Lib/gftools/scripts/gen_push_lists.py, tests/test_push.py
This PR addresses two issues in the push module and push tools. 
1. @eliheuer noticed that some of the knowledge articles were getting removed from the push lists. This is happening because we are popping child items incorrectly.
2. We currently allow `gftools gen-push-lists` to be run a user's local google/fonts repo may not be in an ideal state. You only want to run this tool when your local repo matches the google/fonts main branch, otherwise you get an incorrect pushlist e.g https://github.com/google/fonts/pull/6531/files#diff-f692d04a6bb7f729595b26e06b24f9bc8174de517c2e3d2001fec2a5b2ea28de. I've added the function `branch_matches_google_fonts_main` to catch these situations and raise an error.
=> push: handle knowledge articles better and improve UX

Lib/gftools/builder/__init__.py
GFBuilder.determine_variability() should not fail when given a .glyphspackage.
=> Builder: .glyphspackage

README.md
The current URL on the README has a 404 error.  I believe that this is the new location for the same data.
=> Update glyphsets for designers README link to new path

Lib/gftools/qa.py, Lib/gftools/scripts/qa.py
This improves the robustness of ghtools.qa in a couple of ways:
- Ensures that the fontbakery report is posted as a GH comment just after fontbakery runs, so it is encapsulated from other methods.
- Wraps each function in a decorator which catches exceptions so that an exception in one test does not crash the whole tool.
- Posts a notification of any exceptions/failures to GH.
This is split into fairly small self-contained commits, so may be easiest to review one commit at a time.
=> Make the qa tool more robust

Lib/gftools/scripts/fix_glyphs.py
In #94, Marc says:
> This script is misleading and still appears to be a wip. It doesn't fix anything, [master/bin/gftools-fix-glyphs.py#L38-L43](https://github.com/googlefonts/gftools/blob/master/bin/gftools-fix-glyphs.py?rgh-link-date=2018-11-01T09%3A32%3A51Z#L38-L43)
> There's a fix QA and fix script here (specific to GF), [googlefonts/gf-glyphs-scripts](https://github.com/googlefonts/gf-glyphs-scripts).
Eventually we should get rid of this script, but first we will redirect people to the actual Glyphs fixing script.
=> Deprecate the fix-glyphs script

Lib/gftools/scripts/add_font.py
Fixes #707
Because `sample_text` is a Protobuf "message" (i.e. a nested dictionary), unlike a Python dictionary and unlike a standard scalar field, this has a boolean value of true even if it has no fields. We have to check if there's actually anything in it.
=> Stop duplicating empty sample text

Lib/gftools/scripts/add_ds_subsets.py, Lib/gftools/subsetmerger.py, pyproject.toml
This is a tool I have been using as part of the notobuilder to add (usually Latin) subsets from one font into another. The existing font needs to be in Designspace format. This is expected to be part of the new builder.
Example:
```
gftools-add-ds-subsets --from "Noto Sans" --name "GF_Latin_Core" -o full/MyFont.designspace MyFont.designspace
```
=> Add subset merger

Lib/gftools/builder/_ninja.py
Fixes #727. gftools doesn't install ttfautohint, but does install ttfautohint-py; gftools-autohint wraps this, so we can use this instead of ttfautohint.
=> Use gftools-autohint in ninja builder

Lib/gftools/scripts/add_font.py
=> Only set primary script if we know it

Lib/gftools/builder/__init__.py
This seems to have been dropped during the refactoring.
=> [builder2] Pass --glyph-data to fontmake when converting glyphs to ufo

Lib/gftools/scripts/add_font.py
Fixes #754. The idea is we have a separate threshold for certain subsets (in this case, math and symbols) so that they can be more easily added to the font and not subsetted out.
=> Add the concept of "relaxed subsets"

Lib/gftools/scripts/qa.py
We have a need to pass `-F` to fontbakery for the GF CI. With this patch, we can do `--fontbakery --extra-fontbakery-args="-F" ...`.
=> Allow extra fontbakery args to qa

pyproject.toml
fontbakery >=0.9.0 slimmed down its dependencies and we need to install `fontbakery[googlefonts]` for our profile to work. I'm sure I opened an issue about this but I can't find it now.
=> Add [googlefonts] optional to fontbakery

Lib/gftools/gfgithub.py, Lib/gftools/push/trafficjam.py, Lib/gftools/scripts/manage_traffic_jam.py, tests/test_gfgithub.py
Currently, the GraphQL query will only fetch the first 100 files in a pr. This means that `gen-push-lists` won't add all the files to the `to_sandbox.txt` or `to_production.txt` files for large prs e.g https://github.com/google/fonts/pull/6624.
I thought about implementing a double cursor in the GraphQL query. However, it would've produced a lot of redundant data. My current approach is to fetch files using the rest api, only if the pr contains more than 100 files.
Fixes #737 
cc @simoncozens
=> push: Get all files in a pr

Lib/gftools/scripts/manage_traffic_jam.py
=> manage-traffic-jam: add servers only option

Lib/gftools/qa.py
Will merge once a new fontbakery release is cut. PR implementation will simply log a fatal error and stop all other checks from running.
cc @simoncozens @felipesanches
=> qa: return errcode 1 if fontbakery reports a fatal error

.github/workflows/publish-release.yml
Currently, Twine doesn't support the "trusted publishing" which we now need to use (or an api token but apparently this trusted publishing is preferred). However, trusted publishing is supported by the official pypi gh action, https://github.com/pypa/gh-action-pypi-publish.
=> publish-release: use gh-action-pypi-publish

Lib/gftools/scripts/qa.py
`--extra-fontbakery-args` is a flag on `gftools-qa` which passes *another flag* to fontbakery. Of course this causes problems. If you say `--extra-fontbakery-args --foo` this gets interpreted as a `--foo` flag to `gftools-qa`. `"--foo"` doesn't help because the shell eats the quotes. Apparently the right way to do it is `--extra-fontbakery-args="--foo"` which parses properly. But then `--extra-fontbakery-args="--foo bar"` works on the `gftools-qa` side, but adds a single string "--foo bar" string to fontbakery's argv, which does not parse on that side. Much joy. And you *really* don't want to get into splitting arguments on spaces and feeding them to argv, because `--html "A Report.html"` should be two arguments, not three. And `--extra-fontbakery-args="--foo" "bar"` doesn't work either. …
=> [qa] Allow multiple --extra-fontbakery-args

Lib/gftools/tags.py
This PR simplifies and fixes the parsing logic for parsing the csv that's exported from the Google Sheet. I noticed that Group scores for families were not being parsed correctly e.g the output was missing Alegreya's Serif score. 
I also changed the tagging spreadsheet so Groups and Tags can be inferred more easily.
=> tags: fix _parse_csv logic

Lib/gftools/qa.py
gftools qa can post fontbakery reports back as issue comments. This functionality isn't possible in the google/fonts ci if the pull request has come from a forked repo e.g https://github.com/google/fonts/pull/7136. Github Actions doesn't allow forked repos to access secrets since the user could just steal them. Instead of raising an error, I've decided to add a warn log message instead with the full traceback.
@simoncozens thoughts on this?
=> qa: display log message instead of raising an error if fontbakery report cannot be posted.

Lib/gftools/scripts/drop_hints.py
We should probably run a linter...
=> Fix unimported array (and unused sys) in drop_hints

Lib/gftools/scripts/add_font.py
@emmamarichal pointed out that `add-font` will add `greek-ext` and `cyrillic-ext` subsets to greek and cyrillic families that don't contain the extended glyphs. In nam-files, we have, https://github.com/googlefonts/nam-files/blob/main/Lib/gfsubsets/__init__.py#L203-L204:
```PYTHON
if 100.0 * len(overlap) / len(subset_cps) > target_pct:
results.append((subset, len(overlap), len(subset_cps)))
```
We're multiplying the result by 100 so we're expecting an integer value, not a float which we've currently got. By changing this value to an int, it also matches `--min_pct` int.
=> add-font: fix min_pct_ext default val

Lib/gftools/builder/_ninja.py
For [Danfo](https://github.com/emmamarichal/danfo), the gftools builder is outputting the VF with the filename Danfo-Regular[ELSH].ttf. This PR will instead use the family name from the default source in the designspace, instead of the designspace filename.
cc @emmamarichal @simoncozens
=> builder._ninja: fix vf family name

Lib/gftools/fix.py, Lib/gftools/scripts/rename_font.py, pyproject.toml
Adds a `--just-family` option to gftools-rename-font. This depends on axisregistry 0.4.9, which is not yet released...
=> Allow partial font renames

Lib/gftools/push/items.py, Lib/gftools/push/servers.py, Lib/gftools/push/trafficjam.py, tests/push/test_items.py, tests/push/test_servers.py
I'm now only parsing the text from html files and replacing all whitespace with spaces. I'm finding it's matching items so much better.
Removing the html tags does require regenerating all the cached data. I'll send this via email to the relevant people.
=> manage-traffic-jam: parse Familymeta and Designers better

Lib/gftools/scripts/remap_layout.py
This is a new version of gftools-remap-layout which handles scripts and languages much better. The previous version edited the FeatureList table directly, which caused problems when FeatureList items were shared between languagesystems - a change to one languagesystem ended up being reflected in unexpected places. This one extracts the lookup list for each languagesystem/feature combination, modifies it, and then puts it back again. It also has some fun matching options, so you can do many-to-many:
```
$ gftools-remap-layout -o test2.ttf test.ttf "smcp => test"
INFO:root:[GSUB/DFLT/dflt/test] Adding lookups [1]
INFO:root:[GSUB/latn/dflt/test] Adding lookups [1, 2]
INFO:root:[GSUB/latn/CAT /test] Adding lookups [3]
INFO:root:[GSUB/latn/dflt/smcp] Removing lookups [1, 2] …
```
=> Better gftools-remap-layout

Lib/gftools/builder/__init__.py, Lib/gftools/builder/recipeproviders/__init__.py, Lib/gftools/builder/recipeproviders/googlefonts.py, Lib/gftools/builder/recipeproviders/noto.py, data/test/builder/recipeprovider_noto/TestFamily.glyphs, data/test/builder/recipeprovider_noto/config.yaml, tests/test_builder.py
Its strongly typed YAML objects are a pain in the neck, and are constantly tripping us up with having to add `.data` everywhere. We don't want that, we only want to use it to check the schema and then move on with handling Python dicts as normal.
=> Only use StrictYAML for validation

Lib/gftools/gfgithub.py, Lib/gftools/packager.py, Lib/gftools/utils.py, tests/test_utils.py
@simoncozens I've made a better github url parser and added some tests. I've also added a nifty classmethod so you can instantiate `gfgithub` using just a github url.
Fixes #889
=> Parse github urls better

Lib/gftools/subsetmerger.py
This is needed for adding more than one subset with the same repo owner.
=> gftools-subset: Don't complain if directory exists

Lib/gftools/builder/__init__.py, Lib/gftools/builder/file.py, Lib/gftools/builder/recipeproviders/googlefonts.py, Lib/gftools/builder/recipeproviders/noto.py
This refactors the googlefonts recipe provider to make it more maintainable and share common code; and then it adds a few methods on the end which work out whether or not to generate small cap variants and then builds them.
It's currently experimental, I want to try it on most of the catalogue before merging.
=> Smallcap family builder

Lib/gftools/packager.py
If the git branch command failed for any reason, you would get the error `'NoneType' object has no attribute 'name'` when the code tried to use the (None) `branch` variable. This gives you the output from git.
=> [packager] Improve error message when branch could not be created

Lib/gftools/builder/operations/hbsubset.py
See https://github.com/TypeTogether/Playwrite/issues/38. Running hbsubset causes the post table to be upgraded to version 3.0, but we warn against using that.
=> Keep glyph names when subsetting

Lib/gftools/builder/__init__.py, Lib/gftools/builder/recipeproviders/googlefonts.py
The builder uses a *lot* of temporary files, and when debugging a problem, it's a pain to trace through the `build.ninja` file to determine how `/tmp/4p0m9zvx2l739` was produced from `/tmp/tdpflm38kv4`. With this PR, when the builder config `logLevel` is `DEBUG`, files are named `builder-<target>-<source>-<steps>`. e.g. when you see:
```
/tmp/builder-PlaywriteAUNSW[wght].ttf-Playwrite_MM.glyphspackage-buildVariable-fix-buildStat-subspace
```
you know you are building `PlaywriteAUNSW[wght].ttf` and so far you have started with `Playwrite_MM.glyphspackage` and run the steps `buildVariable`, `fix`, `buildStat` and `subspace`.
=> [builder] Meaningfully named temporary files

Lib/gftools/fix.py, tests/test_fix.py
This started off as a simple PR (add a fix for the [hhea.caretSlopeRun](https://github.com/TypeTogether/Playwrite/issues/43#issuecomment-2076079076) issue caused by interpolating an MVAR table), but it's turned into a bit of rewrite:
* All fix functions are now expected to have a consistent interface: take a TTFont, return a tuple `changed, messages`. Typing has been added to ensure this.
* The "check if the current value of a field is what we expect, and if not, update it, emitting a message" pattern has been abstracted out into a function and used consistently.
* All fix functions check if they are appropriate (have all the tables they need etc.) and return `False, []` if not.
With this in place, `fix_font` becomes a matter of iterating over a list of fix functions.
Additionally, I …
=> [gftools-fix] Restructuring

docs/gftools-builder/README.md
`autohintTTF` is documented, and defaults to `true`, so I incorrectly thought that A) OTFs would be auto hinted by default, which I now see is [not the case for a reason](https://github.com/googlefonts/gftools/issues/838), and B) that it would be documented if it were an option.
This simply documents the option to autohint OTFs, and lets users know it’s off by default.
~Writing this, I’m realizing that it probably needs to a be documented in the `--help` flag of the CLI, too. I’ll try to do that next, and update this PR.~ Oh, never mind: I see that the `--help` flag doesn’t present config options, which makes sense in hindsight.
I welcome edits by maintainers – I’m mostly just trying to helpful in pointing this out with a potential patch.
=> Document `autohintOTF` in gfbuilder docs

Lib/gftools/subsetmerger.py
`ufomerge` doesn't handle sparse masters (glyphs in layers other than the default) yet, so we need to be careful not to merge two targets at different locations into the same source.
=> [subset-merger] Skip sparse masters

Lib/gftools/packager.py
Simply changing the order of each individual steps solved the issue. We previously packaged the family and then created a branch. Now we create a branch, package the family and then commit.
Fixes #947
=> packager: work when gitconfig has rebase=true set

pyproject.toml
Pygit 1.15.0 has breaking api changes. It also doesn't support py3.8. Once py3.8 is EOL, I'll update to the latest version.
Thanks @simoncozens for the report.
=> packager: pin pygit2

Lib/gftools/scripts/fontsetter.py, pyproject.toml, tests/test_fontsetter.py
This adds two new features to gftools-fontsetter:
* A value of the form `"|= 0x123"` will OR the current value of the field with the provided value.
* Multiple keys can be provided in the same configuration file. This allows for calling the same method (`name->setName`) multiple times. (Needed for making things italic.)
=> fontsetter flexibility

Lib/gftools/builder/recipeproviders/googlefonts.py, Lib/gftools/builder/schema.py, docs/gftools-builder/README.md
Fixes #957.
We sometimes have source files containing an `ital` or `slnt` axis, but we require the onboarding of two separate fonts with Roman and Italic joined by style linking and STAT axis. This PR uses `varLib.instancer` to partially instance them along the relevant italic axis and then fixes them up accordingly.
Requires #963.
=> Split Italic and Roman VFs in builder

Lib/gftools/packager.py
From the BeautifulSoup website
> Since it adds whitespace (in the form of newlines), prettify() changes the meaning of an HTML document and should not be used to reformat one. 
We'll write a better one.
Temp fix #967
=> packager: rm html_formatter

Lib/gftools/stat.py
We have a check for this already, but it never fires because it looks for an axis with *name* `ital` and it should look for one with *tag* `ital`. Fixes #976, in a way.
=> Check for ital axis in config file

Lib/gftools/builder/operations/addSubset.py, Lib/gftools/builder/recipeproviders/noto.py, Lib/gftools/scripts/add_ds_subsets.py, Lib/gftools/subsetmerger.py
Sometimes when you're merging one designspace into another, you don't have the same set of masters, and sometimes that's OK - if you have all the corner masters, you can allow the internal masters to go sparse. This allows `add-ds-subsets` to optionally proceed without a full set of matching masters.
=> Allow sparse subsets in add-ds-subsets

Lib/gftools/gfgithub.py, Lib/gftools/scripts/add_ds_subsets.py, Lib/gftools/subsetmerger.py
Closes #986 
In YAML, you can now do:
```yml
- operation: addSubset
directory: latin-sources
subsets:
- from:
repo: googlefonts/some-font@latest # <- the @ bit is new!
path: source/some-font/SomeFont.designspace
force: true
name: GF_Latin_Core
```
Which can take any git reference, or the special value "latest" which grabs the tag from the latest GitHub release
These are appropriately cached in separate folders for org/repo/ref
Support for this is has also been incorporated into `add-ds-subsets`, and I've sprinkled in some type hints in parts of the codebase I've visited
<details>
<summary>Old PR description (outdated)</summary>
In YAML, you can now do:
```yml
repo:
slug: notofonts/latin-greek-cyrillic
ref: e7f1736c5ad0dc2abfc4dcd49ebca50abf612b29
```
Where before repo could only take a …
=> Support Git references in subset merger

Lib/gftools/scripts/add_ds_subsets.py, Lib/gftools/subsetmerger.py, Lib/gftools/utils.py, docs/gftools-builder/README.md, pyproject.toml
Adds support both on commandline and through YAML for glyphs to be excluded by either their name or codepoint.
All of the following now work (and yes, they would work together if something possessed you to do so):
```yml
subsets:
- from:
repo: myorg/myfont
path: source/myfont.designspace
force: true
name: GF_Latin_Core
exclude_codepoints: U+0032 U+0033  # space delimited
exclude_codepoints_file: exclude_codepoints.txt
exclude_glyphs: space a b c  # space delimited
exclude_glyphs_file: exclude_glyph_names.txt
```
Usage docs for the CLI:
```
options:
--exclude-codepoints EXCLUDE_CODEPOINTS
Space-delimited unicodes to exclude
--exclude-codepoints-file EXCLUDE_CODEPOINTS_FILE
Newline delimited file with unicodes to exclude. Allows for comments with either #
or //
--exclude-glyphs …
```
=> Builder subset operation: exclude glyphs by name/codepoint/file

Lib/gftools/scripts/transfer_vtt_hints.py
This PR fixes the following:
- Fix TSI1 table transfers
- Fix TSI3 table transfers by starting with a blank TSI3 table
- Add option to skip TSI1 (component) hints
- Transfer maxp attributes
=> transfer-vtt-hints: Fixes

Lib/gftools/fix.py, Lib/gftools/utils.py
In non-VF days we could just look at all name records up to 255. But there's no upper limit these days, so we look at them all. Fixes #1035
=> Check all name records for Mac IDs

pyproject.toml
Viv reported that installing gftools on her new machine added pygit 1.15.0, which has the same issue as #952.
=> deps: downgrade pygit

Lib/gftools/argparse.py, Lib/gftools/scripts/manage_traffic_jam.py
@simoncozens I've been toying with the idea of having our own `ArgumentParser` class. By default, it'll have the `--show-tracebacks` and `--log-level` commands set to sensible defaults. Once fully implemented, I could replace all ArgumentParsers with our one quite easily.
Still WIP since this may be a footgun idea.
=> Add custom GFArgumentParser

Lib/gftools/fix.py
We allow families that don't have a weight axis such as Kablammo to have user defined fvar instances.
=> fix: retain user instances for families that do not have a wght axis

Lib/gftools/builder/recipeproviders/googlefonts.py, Lib/gftools/builder/schema.py, docs/gftools-builder/README.md
We currently have support in the builder for building small cap variant families; this generalises that idea, with a new configuration option to run a list of operations after the initial font compile. It also adds an option to add a suffix to the output filenames.
Now instead of having to cook up a custom recipe from scratch to handle, say "Cormorant Garamond" (Cormorant + baked-in ss02 feature), you can instead create a separate configuration file like so:
```yaml
sources:
- Cormorant.glyphs
- Cormorant-Italic.glyphs
filenameSuffix: Garamond
postCompile:
- args: '''ss02 -> ccmp'''
operation: remapLayout
- args: --just-family
name: Cormorant Garamond
operation: rename
```
=> Make it easier to build variant families

Lib/gftools/builder/__init__.py, Lib/gftools/builder/file.py, Lib/gftools/builder/fontc.py, Lib/gftools/builder/operations/__init__.py, Lib/gftools/builder/operations/fontc/__init__.py, Lib/gftools/builder/operations/fontc/fontcBuildOTF.py, Lib/gftools/builder/operations/fontc/fontcBuildTTF.py, Lib/gftools/builder/operations/fontc/fontcBuildVariable.py, Lib/gftools/builder/recipeproviders/googlefonts.py
Here is my attempt to add support in `gftools builder` for running `fontc`, and generally making it easier to use in the context of `fontc_crater`.
- adds the `--experimental-fontc` flag, which, if set:
- replaces the `BuildVariable`, `BuildTTF`, and `BuildOTF` operations with alternatives that use `fontc`
- modifies the config so that only _one_ of `buildVariable` and `buildStatic` is `true` (so do not instance variable fonts) and also so that only one of `buildTTF` and `buildOTF` are true (fontc does not currently build CFF outlines, so we turn `buildOTF` off if `buildTTF` is true)
- adds the `--experimental-simple-output=PATH` option, which:
- if modifies the config so that all built fonts end up in one directory
- and does the same config pruning as above, so that we can get the same …
=> Support for fontc and crater

Lib/gftools/builder/fontc.py
If we're identical before autohinting that should be enough for our purposes, and there was a non-deterministic crash in ttfautohint that was causing noise in our crater results.
=> [fontc] Disable autohinting

Lib/gftools/builder/__init__.py, Lib/gftools/builder/fontc.py
When running in the context of crater, gftools builder may be invoked multiple times in parallel, which can cause the generated ninja.build files to overwrite each other.
To fix this, I implemented a scheme where we generate a unique name for the generated build file, so that multiple could exist and be in use for the same project, at the same time.
These files can pile up, though; I had initially thought they were cleaned up by default, but that doesn't seem to be the case.
This patch makes it so we only use this new naming scheme if we're running for crater, and uses the old names otherwise.
It also makes it so we always set the cleanup flag if we're running for crater.
=> [fontc] Only crater needs unique build file names

Lib/gftools/qa.py, Lib/gftools/scripts/qa.py
=> qa: carry on runnning all tools if an error occurs

.github/workflows/test.yml, Lib/gftools/packager/__init__.py, pyproject.toml
I'll probably have to update the packager which I'll do tomorrow. I think Blackrender also has an issue so I'll check that out as well.
Thanks @thundernixon 
Will fix #1050
=> Support py3.13

Lib/gftools/scripts/add_font.py
This allows people to use `gftools-add-font` to create METADATA.pb files outside of the fonts.google.com infrastructure.
=> [add-font] Continue if license detection fails

Lib/gftools/builder/recipeproviders/googlefonts.py
The YAML schema wants this to be a map, but the gftools-fix-font command takes a string, so we need to convert.
=> Make fvarInstanceAxisDflts parameter work, see #1069

Lib/gftools/stat.py
See #469
As of the latest Font Bakery release, [the `no_mac_entries` check has been promoted to the Universal profile](https://github.com/fonttools/fontbakery/blob/main/CHANGELOG.md#0130a0-2024-sep-13); by default, gftools and axisregistry insert Mac names when populating `STAT` and `fvar`, and so boilerplate gftools repositories are FAIL'ing this check out-of-the-box.
This PR makes a partial fix, by preventing Mac names from being added to `STAT`.
This is the right approach for the particular project I am looking at, but I would like to confirm that this is the right fix - as opposed to, e.g., making the Mac names opt-out - to make sure that this will not have unintended consequences for static TTFs destined for legacy environments, or similar.
=> Do not add Mac names when populating the STAT table

Lib/gftools/builder/operations/fontc/__init__.py
Fleshing these out as they arise; noticed a few more causing failures on crater.
=> [fontc] Handle more fontmake args in fontc mode

Lib/gftools/scripts/rename_font.py
Now I can do this:
```
gftools-rename-font --suffix --overwrite Foo.ttf " Dev"
font-v write --dev --sha1 Foo.ttf
```
and get
```
<namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
Foo Dev
</namerecord>
<namerecord nameID="5" platformID="3" platEncID="1" langID="0x409">
Version 2.004;[35feb9f]-dev
</namerecord>
```
which is very handy in CI builds to stop people thinking it's a released font.
=> [rename-font] Add --suffix and --overwrite options

Lib/gftools/scripts/fix_nonhinting.py
doesn't change default behavior but fixes #1078
=> add -q, --quiet and --no-backup options to fix_nonhinting.py

Lib/gftools/builder/__init__.py
Specifically, we don't want to delete the instance_ufos directory if it looks like another instance of gftools might be running in the same location, since it might contain files that are being used.
(The disapearance of this directory has been causing intermittent crater failures.)
=> [fontc] Be more defensive during cleanup

Lib/gftools/utils.py
In `download_family_from_Google_Fonts`; server response changed from absolute URL to relative.
=> [gftools.utils] Absolutize possibly relative URL

Lib/gftools/builder/operations/fontc/__init__.py
My understanding is that this was the original intention of the code, but that the fall-through case performs the task of skipping too. (cc @cmyr would benefit from your know-how here, is this indeed what we want to support? :mag_right: )
Merging would lead to additional fails on crater, but in at least some cases (e.g. the Jersey family) for families that have a low % match already owing to an unsupported filter; this would become more explicit.
<sub>Note: this is a personal contribution independent of my employer, and so I've submitted from a fork under my personal profile and email to make this distinction</sub>
=> Raise an error when an unknown fontmake filter is provided to fontc

Lib/gftools/builder/__init__.py, Lib/gftools/builder/fontc.py, Lib/gftools/builder/operations/fontc/__init__.py
In ttx_diff.py we'd like control whether to pass the `--no-production-names` flag down to fontc and fontmake or not..
Which means, renaming glyphs to their final production names by default, but sometimes when useful keep original human-readable glyph names for debugging.
I added a catch-all flag which means we won't need extra flags if we'd like to support any additional options.
=> [builder] add --experimental-extra-arg flag to pass down extra arguments to compilers

Lib/gftools/builder/__init__.py, Lib/gftools/builder/fontc.py, Lib/gftools/builder/operations/fontc/__init__.py
following conversation https://github.com/googlefonts/gftools/pull/1106#discussion_r2087316780
This reverts commit 194befe23a73f6a51bd30c2e10b99128e635bcf7, reversing changes made to ec251ef0908dfb49f34748755ee201270d5cdcb2.
We shall create a modified temporary config instead with our desired `extraFontmakeArgs`
=> Revert "Merge pull request #1106 from googlefonts/experimental-extra-args@

bin/install_rust_binaries.sh
Thought it would be nice to offer users an easy way to install fontc, fontspector and diffenator3 since they can be optionally used in this repo.
I've intentionally chosen to install the binaries to the currently active python venv since this allows users to potentially have specific versions for individual projects. I don't want this script to overwrite binaries that may exist in a user's `/usr/local/bin` dir.
Only real concern I have is the version for each tool is hardcoded in the url. It may be preferable to get the latest but I guess I'll need to use something like jq to get this info.
Once merged, users can simply install by doing:
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/googlefonts/gftools/refs/heads/main/bin/install_rust_binaries.sh)"`
=> install_rust_binaries.sh: added

Lib/gftools/scripts/add_font.py, Lib/gftools/scripts/lang_support.py, Lib/gftools/scripts/push_stats.py, Lib/gftools/utils.py, bin/gftools, tests/push/test_items.py
pkg_resources has been removed in python 3.12+.
Maybe I'm getting old but I hate this type of change. There's obviously a good reason for it but I'm just tired.
The migration guide was super handy, https://importlib-resources.readthedocs.io/en/latest/migration.html#pkg-resources-resource-filename
=> Replace pkg_resources with importlib_resources
